#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.5

$HOME/.config/polybar/launch.sh &
~/.fehbg
dunst &
